services:
  app:
    build:
      context: .
      no_cache: true
    image: flickr-gallery_img
    volumes:
      - ./app:/app
    working_dir: /app
    container_name: "flickr-gallery_ctn"
    hostname: "flickr-gallery_hst"
    ports:
      - 2469:2469
    entrypoint: /bin/sh -c "yarn && yarn dev"
    # entrypoint: ["sh", "-c", "sleep 2073600"] debug mode
