services:
  app:
    build: .
    image: flickr-gallery_img
    volumes:
      - .:/app
    working_dir: /app
    container_name: "flickr-gallery_ctn"
    hostname: "flickr-gallery"
    ports:
      - 2469:2469
    entrypoint: [ "yarn", "dev" ]
    # entrypoint: ["sh", "-c", "sleep 2073600"] debug mode
