name: Keep Render Alive

on:
  schedule:
    - cron: "*/14 * * * *" # A cada 14 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: curl -s https://flickr-public-photos.onrender.com || echo "Failed"
